USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'MatKhauManh@123';
GO

CREATE CERTIFICATE QLBONGDA_TDE_Cert
FROM FILE = 'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\QLBONGDA_TDE_Cert.cer'
WITH PRIVATE KEY 
(
    FILE = 'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\QLBONGDA_TDE_Cert.pvk',
    DECRYPTION BY PASSWORD = 'Backup@123!'
);
GO


