USE [master]
GO
CREATE LOGIN [BDAdmin] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDAdmin] FOR LOGIN [BDAdmin]
GO
USE [QLBONGDA]
GO
ALTER ROLE [db_owner] ADD MEMBER [BDAdmin]
GO
