USE [master]
GO
CREATE LOGIN [BDBK] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDBK] FOR LOGIN [BDBK]
GO
USE [QLBONGDA]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [BDBK]
GO
