USE [master]
GO
CREATE LOGIN [BDProfile] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDProfile] FOR LOGIN [BDProfile]
GO
use [master]
GO
GRANT ALTER TRACE TO [BDProfile]
GO
