use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU6] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau1] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau10] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau3] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau4] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau9] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU8] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU5] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau2] TO [BDRead]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU7] TO [BDRead]
GO
