USE [master]
GO
CREATE LOGIN [BDRead] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDRead] FOR LOGIN [BDRead]
GO
USE [QLBONGDA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [BDRead]
GO
