USE [master]
GO
CREATE LOGIN [BDU01] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDU01] FOR LOGIN [BDU01]
GO
USE [QLBONGDA]
GO
GRANT CREATE TABLE TO [BDU01]
GO