USE [master]
GO
CREATE LOGIN [BDU02] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDU02] FOR LOGIN [BDU02]
GO
use [QLBONGDA]
GO
GRANT UPDATE TO [BDU02]
GO
use [QLBONGDA]
GO
DENY CREATE TABLE TO [BDU02]
GO
use [QLBONGDA]
GO
DENY DELETE TO [BDU02]
GO
