USE [master]
GO
CREATE LOGIN [BDU04] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDU04] FOR LOGIN [BDU04]
GO
use [QLBONGDA]
GO
GRANT SELECT ON [dbo].[CAUTHU] TO [BDU04]
GO
use [QLBONGDA]
GO
GRANT UPDATE ON [dbo].[CAUTHU] TO [BDU04]
GO
use [QLBONGDA]
GO
DENY SELECT ON [dbo].[CAUTHU] ([NGAYSINH]) TO [BDU04]
GO
use [QLBONGDA]
GO
DENY UPDATE ON [dbo].[CAUTHU] ([VITRI]) TO [BDU04]
GO
use [QLBONGDA]
GO
GRANT DELETE ON [dbo].[CAUTHU] TO [BDU04]
GO
use [QLBONGDA]
GO
GRANT INSERT ON [dbo].[CAUTHU] TO [BDU04]
GO
