use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau1] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau3] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau4] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau2] TO [BDU03]
GO
