USE [master]
GO
CREATE LOGIN [BDU03] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [QLBONGDA]
GO
CREATE USER [BDU03] FOR LOGIN [BDU03]
GO
use [QLBONGDA]
GO
GRANT DELETE ON [dbo].[CAULACBO] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT INSERT ON [dbo].[CAULACBO] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT SELECT ON [dbo].[CAULACBO] TO [BDU03]
GO
use [QLBONGDA]
GO
GRANT UPDATE ON [dbo].[CAULACBO] TO [BDU03]
GO
