use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU5] TO [BDU01]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU6] TO [BDU01]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU7] TO [BDU01]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCAU8] TO [BDU01]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau9] TO [BDU01]
GO
use [QLBONGDA]
GO
GRANT EXECUTE ON [dbo].[SPCau10] TO [BDU01]
GO
