use QLBONGDA
go

-- vCau1
CREATE VIEW vCau1 AS
SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
FROM CAUTHU CT 
JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB 
JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
WHERE CLB.TENCLB = N'SHB Đà Nẵng' AND QG.TENQG = N'Brazil'

--vCau2
CREATE VIEW vCau2 AS
SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, 
       CLB1.TENCLB AS TENCLB_CHU, 
       CLB2.TENCLB AS TENCLB_KHACH, 
       TD.KETQUA
FROM TRANDAU TD 
JOIN SANVD SVD ON TD.MASAN = SVD.MASAN 
JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB 
JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.VONG = 3 AND TD.NAM = 2009

--vCau3
CREATE VIEW vCau3 AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV 
JOIN HLV_CLB HC ON HC.MAHLV = HLV.MAHLV 
JOIN CAULACBO CLB ON HC.MACLB = CLB.MACLB 
JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam'

--vCau4
CREATE VIEW vCau4 AS
SELECT CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI, COUNT(CTNN.MACLB) AS SO_CAU_THU_NGOAI
FROM CAULACBO CLB 
JOIN SANVD SVD ON SVD.MASAN = CLB.MASAN 
JOIN (
    SELECT CT.MACLB
    FROM CAUTHU CT 
    JOIN QUOCGIA QG ON QG.MAQG = CT.MAQG
    WHERE QG.TENQG != N'Việt Nam'
) CTNN ON CTNN.MACLB = CLB.MACLB
GROUP BY CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI
HAVING COUNT(CTNN.MACLB) > 2

--vCau5
CREATE VIEW vCau5 AS
SELECT T.TENTINH, COUNT(CT.MACT) AS SO_CAU_THU
FROM TINH T
JOIN CAULACBO CLB ON CLB.MATINH = T.MATINH 
JOIN CAUTHU CT ON CT.MACLB = CLB.MACLB
WHERE CT.VITRI = N'Tiền đạo'
GROUP BY T.TENTINH

--vCau6
CREATE VIEW vCau6 AS
SELECT CLB.TENCLB, T.TENTINH
FROM CAULACBO CLB
JOIN TINH T ON T.MATINH = CLB.MATINH
JOIN BANGXH BXH ON BXH.MACLB = CLB.MACLB
WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = 1

--vCau7
CREATE VIEW vCau7 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN HLV 
JOIN HLV_CLB HC ON HC.MAHLV = HLV.MAHLV
WHERE HC.VAITRO IS NOT NULL AND HLV.DIENTHOAI IS NULL

--vCau8
CREATE VIEW vCau8 AS
SELECT HLV.*
FROM HUANLUYENVIEN HLV
JOIN QUOCGIA QG ON QG.MAQG = HLV.MAQG
WHERE QG.TENQG = N'Việt Nam'

EXCEPT

SELECT HLV.*
FROM HUANLUYENVIEN HLV
JOIN QUOCGIA QG ON QG.MAQG = HLV.MAQG
JOIN HLV_CLB HC ON HC.MAHLV = HLV.MAHLV
WHERE QG.TENQG = N'Việt Nam'

--vCau9
CREATE VIEW vCau9 AS
WITH CLB_DAU_BANG AS (
    SELECT MACLB
    FROM BANGXH
    WHERE NAM = 2009 AND VONG = 3 AND HANG = 1
)
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD
JOIN SANVD SVD ON SVD.MASAN = TD.MASAN
JOIN CAULACBO CLB1 ON CLB1.MACLB = TD.MACLB1
JOIN CAULACBO CLB2 ON CLB2.MACLB = TD.MACLB2
JOIN CLB_DAU_BANG CDB ON CDB.MACLB IN (TD.MACLB1, TD.MACLB2)
WHERE TD.VONG <= 3 AND TD.NAM = 2009

--vCau10
CREATE VIEW vCau10 AS
WITH CLB_BET_BANG AS (
    SELECT MACLB
    FROM BANGXH
    WHERE NAM = 2009 AND VONG = 3 
    AND HANG = (SELECT MAX(HANG) FROM BANGXH WHERE NAM = 2009 AND VONG = 3)
)
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD
JOIN SANVD SVD ON SVD.MASAN = TD.MASAN
JOIN CAULACBO CLB1 ON CLB1.MACLB = TD.MACLB1
JOIN CAULACBO CLB2 ON CLB2.MACLB = TD.MACLB2
JOIN CLB_BET_BANG CBB ON CBB.MACLB IN (TD.MACLB1, TD.MACLB2)